### ISSUE TITLE
More CSS - spacing

### ISSUE THREAD

**Issue by alfonsotech** [JPGothro/Portfolio#23]
- I'd like to see more space above and below the header text that reads "Portfolio of Projects"
  -I'd like to see less space below the text that reads "Projects by John", and maybe also more space above it so that it visually hangs together with the list of projects.
  -I'd like the list of projects (title, and the triangle) to be bigger; anything you can do to make it obvious that it's clickable may also be good.
  -Colors: you may want to think about group of colors that go together (color pairs), instead of picking a couple colors independently. Try: https://www.materialpalette.com/

**Comment by JPGothro** [comment]
- Modified spacing around the headers.
- Modified the font size for Projects.
- Have not changed colors. That will be turned into a separate issue.
